/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poste1client;

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author toshiba
 */
public class Accueil_Client extends javax.swing.JFrame {
    public Dimension getPreferredSize() {
return new Dimension (780,530); // largeur et hauteur préférées
}
    /**
     * Creates new form accccc
     */
    public Accueil_Client() {
        initComponents();
          this.setLocationRelativeTo(null);     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new komponenMakeOver.buttonMakeOver();
        ipa = new javax.swing.JTextField();
        limite = new komponenMakeOver.buttonMakeOver();
        btnjdesc = new komponenMakeOver.buttonMakeOver();
        Client = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new komponenMakeOver.buttonMakeOver();
        jButton2 =  new komponenMakeOver.buttonMakeOver();
        code = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accueil  poste 1 client");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 0));
        jButton3.setText("Saisie votre adresse IP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(260, 80, 250, 30);

        ipa.setText("127.0.0.1");
        getContentPane().add(ipa);
        ipa.setBounds(260, 110, 250, 60);
        getContentPane().add(limite);
        limite.setBounds(-10, 70, 780, 10);

        btnjdesc.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        btnjdesc.setForeground(new java.awt.Color(255, 255, 0));
        btnjdesc.setText(" .::  La cryptographie pour communiquer en toute sécurité  ::.");
        btnjdesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjdescActionPerformed(evt);
            }
        });
        getContentPane().add(btnjdesc);
        btnjdesc.setBounds(-1, 0, 770, 80);

        Client.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Client.setForeground(new java.awt.Color(255, 255, 0));
        Client.setText("Client");
        getContentPane().add(Client);
        Client.setBounds(480, 380, 150, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/c527cd017abafa.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 130, 320, 330);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1326279970_Login Manager.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 320, 180, 140);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Démarer");
        jButton1.setToolTipText("lorsque vous cliquer sur ce bouton vous allez  trouver la page concernant la generation de clé avec Diffie hellman");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 140, 170, 60);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Déconnecter");
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 230, 170, 60);

        code.setBackground(new java.awt.Color(255, 255, 255));
        code.setForeground(new java.awt.Color(255, 153, 0));
        code.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fontblue.png"))); // NOI18N
        code.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                codeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(code);
        code.setBounds(-6, -6, 770, 510);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 100, 50, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String sip=null; 
     /* sip=ipa.getText();
        if(sip==null){  
                  JOptionPane.showMessageDialog(null, " svp seasie votre adresse IP "  );}*/
          
     
       
          
        //else{
        // RC4_Client frame=new RC4_Client();
  /*frame.setVisible(true);//show();
RC4_Client .clé.setText(this.jhash.getText());*/
      RC4_Client.ip =  sip;//ipa.getText();
       Hellman_Client.ip =  sip;//ipa.getText();
         Hellman_Client frame=new Hellman_Client();
        frame.setVisible(true);//show();}*/
    //   }
      //frame.mclient();
    // frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    // frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2MouseEntered

    private void btnjdescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjdescActionPerformed
        // TODO add your handling code here:
        /* bouton juste pour  lestitique hihhihihiiiiiiiiii!!!!!!!!*/
    }//GEN-LAST:event_btnjdescActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void codeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_codeAncestorAdded
        // TODO add your handling code here:
         
                  JOptionPane.showMessageDialog(null, " svp seasie  adresse IP votre serveur"  );
          
    }//GEN-LAST:event_codeAncestorAdded

    /**
     * @param args the command  arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil_Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Client;
    private javax.swing.JButton btnjdesc;
    private javax.swing.JLabel code;
    private javax.swing.JTextField ipa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton limite;
    // End of variables declaration//GEN-END:variables
}
