/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server_poste_2;

//import poste1client.*;
import java.awt.Dimension;
import java.net.Socket;
import javax.swing.JFrame;

/**
 *
 * @author toshiba
 */
public class Accueil_Server extends javax.swing.JFrame {
    public Dimension getPreferredSize() {
return new Dimension (780,580); // largeur et hauteur préférées
} 
    /**
     * Creates new form accccc
     */
    public Accueil_Server() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnjdesc = new komponenMakeOver.buttonMakeOver();
        limite = new komponenMakeOver.buttonMakeOver();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new komponenMakeOver.buttonMakeOver();
        jButton2 = new komponenMakeOver.buttonMakeOver();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accueil  poste 2 server");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Serveur");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 384, 80, 20);

        btnjdesc.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        btnjdesc.setForeground(new java.awt.Color(255, 255, 0));
        btnjdesc.setText(" .::  La cryptographie pour communiquer en toute sécurité  ::.");
        btnjdesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjdescActionPerformed(evt);
            }
        });
        getContentPane().add(btnjdesc);
        btnjdesc.setBounds(-1, 0, 770, 80);
        getContentPane().add(limite);
        limite.setBounds(0, 80, 780, 10);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/c527cd017abafa.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 170, 320, 330);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1326279970_Login Manager.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 390, 190, 140);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Démarer");
        jButton1.setToolTipText("lorsque vous cliquer sur ce bouton vous allez  trouver la page concernant la generation de clé avec Diffie hellman");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 200, 170, 60);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Déconnecter");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 320, 170, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/light_texture2295.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-6, -6, 770, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /*if((JButton)e.getSource()==bouton) 
{ 
new NouvelFenetre().setVisible(true); 
this.setVisible(false); */
        
        Hellman_Server frame=new Hellman_Server();
      
     //*/frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.setVisible(true);
       // frame.show();
       // frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
   /// frame.doLayout();//setVisible(true);
       // frame.mserver();
  

        /* Hellmanbluserver H=new Hellmanbluserver();
      // Thread t=new Thread( (Runnable) H);
       H.run();*/

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnjdescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjdescActionPerformed
        // TODO add your handling code here:
        /* bouton juste pour  lestitique hihhihihiiiiiiiiii!!!!!!!!*/
    }//GEN-LAST:event_btnjdescActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil_Server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnjdesc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton limite;
    // End of variables declaration//GEN-END:variables
}
